malakrobo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  l_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_left_wheel
    pid: {p: 200.0, i: 1.0, d: 0.50}
  r_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_right_wheel
    pid: {p: 200.0, i: 1.0, d: 0.50}
